### PR TITLE
Add documentation to the API

### PR DESCRIPTION
**Pull request by haumacher**
The typecast library so far looks like a literal translation of the OpenType format specification to Java. It's a great starting point for learning and experimenting with font details. Unfortunately, only the structures and field names are "translated" (what an amazing bunch of work!), but not the corresponding documentation. I'd like to add the corresponding field documenation from the specification https://docs.microsoft.com/en-us/typography/opentype/spec/ to the JavaDoc of the fields and classes. A showcase can be seen in https://github.com/haumacher/typecast/blob/84cdf4db031f9e17ca14b3b901a24e702e06baac/src/main/java/net/java/dev/typecast/ot/table/HeadTable.java

I've no idea what consequences this would have regarding the license of the library and the license of the specification (I have not found any reference to a license in the OpenType specification).

Are you willing to accept such a contribution?

### CODE REVIEW

**Comment by dcsch** [comment]
I would assume that the Microsoft spec is copyrighted material, as indicated on the footer of the Microsoft website. I guess the question is whether quoting the spec in this project is considered "fair use."

**Comment by haumacher** [comment]
Good point.

https://docs.microsoft.com/en-us/legal/termsofuse#personal-and-non-commercial-use-limitation states:

> Unless otherwise specified, the Services are for your personal and non-commercial use. You may **not** modify, **copy**, distribute, transmit, publicly display, perform, reproduce, publish, license, **create derivative works** from, transfer or sell any information, software, products or services obtained from the Services (except for your own, personal, non-commercial use) without prior written consent from Microsoft.

With or without the comments - is such a parsing library considered _derivative works_?

https://docs.microsoft.com/en-us/legal/termsofuse#notice-specific-to-documents-available-on-this-website states:

> Permission to use Documents (such as white papers, press releases, datasheets and FAQs) from the Services is granted, provided that (1) the below copyright notice appears in all copies and that both the copyright notice and this permission notice appear, (2) use of such Documents from the Services is for informational and non-commercial or personal use only and will **not be copied** or posted on any network computer or broadcast in any media, and (3) **no modifications** of any Documents are made.

Is quoting the specs in source code comments considered _copying_ or is creating a parser library with quotes from a format specification considered __modification__ of the spec?

> Distribution outside the classroom requires express written permission.

Unfortunately no hint is given where to ask for such a permission...

**Comment by dcsch** [comment]
It would be great to include the bug fixes in this PR, but I'm still hesitant about including the Microsoft material. Would it be possible to create a PR without the documentation?

**Comment by haumacher** [comment]
Hi @dcsch, I've filed a new PR #13, that consolidates all changes of this PR without the copied Microsoft material. I replaced the extensive quotes of the specification with links to the corresponding pages of the spec. Hope this is OK for you.

**Pull request closed without merging**
